### ISSUE TITLE
The linting and base images should fix linter versions

### ISSUE THREAD

**Issue by skitt** [submariner-io/shipyard#884]
The `shipyard-linting` and base images install the latest version of `markdownlint-cli` and `gitlint` (in the linting image only; the base image installs the Fedora package which is supposed to maintain compatibility in a given release). This can cause unplanned changes in linting requirements, making it harder to get unrelated patches merged. See #874 for one example of the many patches required recently following a version bump in `markdownlint-cli`.

The linting image should install known versions of `markdownlint-cli` and `gitlint`; the base image should install a known version of `markdownlint-cli`.

**Comment by dfarrell07** [comment]
We install gitlint with pip (which requires installing pip as well) because it's not shipped in the container's distro (it is shipped in Fedora, but this container is Alpine). Can't simplify that.

I asked Stephen about also pinning the packages installed via the OS's package manager, but that doesn't work elegantly as the package manager basically-pins the version to the OS version.
